apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://traefik.github.io/charts
  chart: traefik
  version: "v39.0.2"
  targetNamespace: kube-system
  valuesContent: |-
    logs:
      access:
        enabled: true
        format: json
        fields:
          defaultMode: keep
    metrics:
      prometheus:
        entryPoint: metrics
    tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
